Mimx8mm ecspi
bytesatwork/bytesatwork-zepyhr pull request #2
Opened 2022-02-10 08:32 UTC by dariis

2022-02-24 07:42 UTC, kaebe requested changes

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/Kconfig.mcux_ecspi
> +# TODO: DMA
Please remove

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +	uint8_t cs_delay; /*!< SS delay time (master only) */
Is this in milli? If yes then why not cs_delay_ms

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +		if (remainder == 2) {
why not elseif?

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +		if (remainder == 2) {
why not else if

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +	return transceive(dev, spi_cfg, tx_bufs, rx_bufs, false, NULL);
why another function

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +	return transceive(dev, spi_cfg, tx_bufs, rx_bufs, true, async);
This is not really async.
Would it not be better not register the ansnc part?

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +	.transceive_async = ecspi_mcux_transceive_async,
I would not register this...

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +static int transceive(const struct device *dev,
naming scheme different then other functions

2022-02-24 07:42 UTC, kaebe commented on drivers/spi/spi_mcux_ecspi.c
> +		LOG_DBG("%s source handled", dev->name);
Loging in interrupt usually not the best idea.

2022-02-25 07:00 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +LOG_MODULE_REGISTER(spi_mcux_ecspi, CONFIG_SPI_LOG_LEVEL);
Used the same naming as in `spi_mcux_lpspi.c`, should I change it?
mcux represents the used HAL whereas imx represents the processor family.

2022-02-25 07:06 UTC, dariis commented on drivers/spi/Kconfig.mcux_ecspi
> +# TODO: DMA
thanks.

2022-02-25 07:07 UTC, dariis commented on drivers/spi/Kconfig.mcux_ecspi
> +# TODO: DMA
duplicate.

2022-02-25 07:12 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +	uint8_t cs_delay; /*!< SS delay time (master only) */
No it is in clock cycles.
https://github.com/bytesatwork/bytesatwork-zepyhr/blob/9909bc47fc4508df220d379ab54c6bbda6ff909c/dts/bindings/spi/nxp%2Cimx-ecspi.yaml#L24

Should I change it, i saw a driver where it gets calculated?

2022-02-25 07:18 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +		if (remainder == 2) {
:thinking: :man_shrugging: 
thanks.

2022-02-25 07:18 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +		if (remainder == 2) {
:thinking: :man_shrugging: 
thanks.

2022-02-25 07:27 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +	return transceive(dev, spi_cfg, tx_bufs, rx_bufs, false, NULL);
Keep it as in the other SPI drivers.
Here it could be extended with DMA.

2022-02-25 07:41 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +	return transceive(dev, spi_cfg, tx_bufs, rx_bufs, true, async);
I think we are always transferring async, we do not bitbang.
`interrupts:` https://github.com/bytesatwork/bytesatwork-zepyhr/blob/9909bc47fc4508df220d379ab54c6bbda6ff909c/dts/bindings/spi/nxp%2Cimx-ecspi.yaml#L15

As in other drivers only the `spi_context_lock` differs, which I assume supports signaling to the application (`k_poll_signal`).

2022-02-25 07:49 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +	.transceive_async = ecspi_mcux_transceive_async,
I would keep it, because of comment above https://github.com/bytesatwork/bytesatwork-zepyhr/pull/2#discussion_r814539407.

2022-02-25 07:49 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +static int transceive(const struct device *dev,
thanks.

2022-02-25 07:51 UTC, dariis commented on drivers/spi/spi_mcux_ecspi.c
> +		LOG_DBG("%s source handled", dev->name);
:thinking: good point.

2022-03-02 08:08 UTC, kaebe approved these changes

2022-03-02 09:36 UTC, merged